# -*- coding: utf-8 -*-
"""Getting_Started.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GPA9t-BKgnoyeCHuCGSKEypM19U8CYwC

**Getting Started in IPython**
"""


def square(x):
  """Return the square of x."""
  return x ** 2


def add_numbers(x, y):
  """
  Add two numbers together

  Returns
  -------
  the_sum : type of arguments
  """
  return x + y

print(f'sum = {add_numbers(5,6)}')

def multiply_numbers(x, y):
  """
  Multiply two numbers together

  Returns
  -------
  the_product : type of arguments
  """
  return x * y